apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: {{ template "name" . }}
  namespace: grafana-monitoring  
spec:
  resyncPeriod: 30s
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  json: |
    {{ .Values.dashboardJson | indent 4 }}
  resyncPeriod: 1m